import Link from "next/link";
import { quests, student } from "../lib/mock-data";

function Kibo({ small = false }: { small?: boolean }) {
  return <div className={`relative mx-auto aspect-square ${small ? "w-28" : "w-48 sm:w-56"}`} aria-label="Kibo, teman belajar EduVerse" role="img"><div className="absolute inset-2 rounded-full bg-[#ffdc78] opacity-70 blur-2xl" /><div className="absolute bottom-1 left-1/2 h-3 w-28 -translate-x-1/2 rounded-full bg-[#17345d]/15 blur-sm" /><div className="absolute left-[18%] top-[18%] h-[58%] w-[64%] rounded-[44%] border-[7px] border-[#17345d] bg-[#7dd8d1] shadow-[0_8px_0_#4ba9ad]"><div className="absolute -top-[20%] left-1/2 h-9 w-2 -translate-x-1/2 rounded-full bg-[#17345d]" /><div className="absolute -top-[34%] left-1/2 grid size-9 -translate-x-1/2 place-items-center rounded-full border-3 border-[#17345d] bg-[#ffce4a] text-sm text-[#17345d]">✦</div><div className="absolute left-[16%] top-[37%] size-3 rounded-full bg-[#17345d]" /><div className="absolute right-[16%] top-[37%] size-3 rounded-full bg-[#17345d]" /><div className="absolute left-1/2 top-[50%] h-4 w-8 -translate-x-1/2 rounded-b-full border-b-3 border-[#17345d]" /><div className="absolute -left-[16%] top-[42%] h-16 w-8 rotate-[22deg] rounded-full border-5 border-[#17345d] bg-[#ffb86b]" /><div className="absolute -right-[16%] top-[42%] h-16 w-8 rotate-[-22deg] rounded-full border-5 border-[#17345d] bg-[#ffb86b]" /></div></div>;
}

function ProgressBar({ value, className = "" }: { value: number; className?: string }) {
  return <div className={`h-3 overflow-hidden rounded-full bg-[#d7e6ed] ${className}`} role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100} aria-label={`${value}% progress`}><div className="h-full rounded-full bg-[#f4aa32] transition-all" style={{ width: `${value}%` }} /></div>;
}

export default function DashboardPage() {
  return <div className="min-h-screen overflow-hidden bg-[#f7fbff] text-[#17345d]"><main className="mx-auto max-w-7xl px-5 pb-12 pt-8 sm:px-8 sm:pt-10 lg:px-10"><section className="relative overflow-hidden rounded-[30px] border-2 border-[#17345d] bg-[#dff3ef] px-6 py-7 shadow-[8px_8px_0_#17345d] sm:px-10 sm:py-9 lg:px-14"><div className="absolute -right-12 -top-16 size-48 rounded-full border-[22px] border-[#ffce4a]/60" /><div className="relative grid items-center gap-6 md:grid-cols-[1fr_auto] md:gap-10"><div><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-[#26858b]">Base camp · Math Kingdom</p><h1 className="mt-2 max-w-xl text-4xl font-black leading-tight tracking-tight sm:text-5xl">Selamat datang kembali, {student.name}! <span aria-hidden="true">👋</span></h1><p className="mt-3 max-w-lg text-base leading-7 text-[#365477]">Siap melanjutkan petualangan belajarmu?</p><div className="mt-5 inline-flex items-center gap-3 rounded-2xl border-2 border-[#17345d] bg-white px-4 py-3 text-sm font-extrabold shadow-[4px_4px_0_#17345d]">Kibo: “Yuk, kita lanjutkan petualangan hari ini!”</div></div><Kibo /></div></section>
    <section className="mt-12 grid gap-7 lg:grid-cols-[1.35fr_0.65fr]"><div className="relative overflow-hidden rounded-[30px] border-2 border-[#17345d] bg-[#17345d] p-7 text-white shadow-[8px_8px_0_#0d2341] sm:p-9"><div className="absolute -right-8 -top-10 size-48 rounded-full border-[25px] border-[#4ba9ad]/40" /><div className="relative max-w-xl"><p className="text-sm font-extrabold uppercase tracking-[0.18em] text-[#ffcf58]">World 01 · Main adventure</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Math Kingdom</h2><p className="mt-4 max-w-lg leading-7 text-[#d9e8f0]">Jelajahi kerajaan matematika dan selesaikan quest untuk mendapatkan XP.</p><div className="mt-7 flex flex-wrap items-end justify-between gap-5"><div className="min-w-48 flex-1"><div className="mb-2 flex justify-between text-sm font-extrabold"><span>Perjalananmu</span><span>{student.progress}%</span></div><ProgressBar value={student.progress} /></div><Link href="/math-kingdom" className="inline-flex items-center rounded-2xl bg-[#f4aa32] px-5 py-3 font-extrabold text-[#17345d] shadow-[0_4px_0_#d98b1d] transition hover:-translate-y-1 hover:bg-[#ffc451] focus:outline-none focus:ring-4 focus:ring-[#ffcf58]/50 active:translate-y-1 active:shadow-none">Jelajahi Math Kingdom <span className="ml-2">→</span></Link></div></div><div className="absolute bottom-3 right-8 hidden text-7xl font-black text-[#ffcf58]/30 sm:block">＋</div></div><aside className="rounded-[30px] border-2 border-[#17345d] bg-[#fff4cf] p-7 shadow-[6px_6px_0_#17345d] sm:p-8"><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-[#a66e14]">Progress singkat</p><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div><p className="text-2xl font-black">{student.xp}</p><p className="mt-1 text-xs font-bold text-[#617692]">XP</p><p className="text-[11px] font-bold text-[#91a3b6]">/ {student.xpGoal}</p></div><div className="border-x border-[#e8d89e]"><p className="text-2xl font-black">{student.questsCompleted}</p><p className="mt-1 text-xs font-bold text-[#617692]">Quest</p><p className="text-[11px] font-bold text-[#91a3b6]">/ {student.questsTotal}</p></div><div><p className="text-2xl font-black">{student.progress}%</p><p className="mt-1 text-xs font-bold text-[#617692]">Progress</p></div></div><ProgressBar value={student.progress} className="mt-6" /><Link href="/progress" className="mt-6 inline-flex font-extrabold text-[#26858b] underline decoration-2 underline-offset-4 hover:text-[#17345d] focus:outline-none focus:ring-2 focus:ring-[#26858b]">Lihat Progress →</Link></aside></section>
    <section className="mt-12"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-extrabold uppercase tracking-[0.18em] text-[#26858b]">Peta quest</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Petualangan Math Kingdom</h2></div><span className="hidden text-sm font-extrabold text-[#617692] sm:block">{student.questsCompleted} dari {student.questsTotal} selesai</span></div><div className="mt-6 grid gap-5 md:grid-cols-3">{quests.map((quest) => <Link href="/quest" key={quest.title} className={`group relative min-h-56 rounded-[25px] border-2 border-[#17345d] ${quest.color} p-6 shadow-[6px_6px_0_#17345d] transition hover:-translate-y-1 focus:outline-none focus:ring-4 focus:ring-[#8fd9d1]`}><span className="absolute right-5 top-5 grid size-9 place-items-center rounded-full bg-[#17345d] text-xs font-black text-white">{quest.number}</span><div className="grid size-12 place-items-center rounded-full bg-[#17345d]/15 text-2xl font-black">{quest.symbol}</div><h3 className="mt-5 max-w-[13rem] text-xl font-black">{quest.title}</h3><p className="mt-2 text-sm font-bold text-[#365477]">{quest.type}</p><span className="absolute bottom-5 rounded-full bg-white/75 px-3 py-1 text-xs font-extrabold">{quest.status}</span></Link>)}</div></section>
    <section className="mt-12 grid items-center gap-5 rounded-[25px] border-2 border-[#17345d] bg-white px-6 py-6 shadow-[6px_6px_0_#17345d] sm:grid-cols-[auto_1fr] sm:px-8"><Kibo small /><div><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-[#ef9e27]">Kibo’s Tip</p><p className="mt-2 max-w-3xl text-base font-bold leading-7 text-[#365477]">Kalau menemukan soal yang sulit, jangan buru-buru menyerah. Coba pecah soalnya menjadi langkah-langkah kecil!</p></div></section>
  </main>
  </div>
}
